// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package db

import (
	"context"
)

const deleteAdminLoginById = `-- name: DeleteAdminLoginById :exec
UPDATE Admin
SET isdelete = 1
WHERE id = $1
`

func (q *Queries) DeleteAdminLoginById(ctx context.Context, adminID int32) error {
	_, err := q.db.Exec(ctx, deleteAdminLoginById, adminID)
	return err
}

const getAdminById = `-- name: GetAdminById :one
SELECT id, email, password, isdelete FROM Admin
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdminById(ctx context.Context, adminID int32) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminById, adminID)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Isdelete,
	)
	return i, err
}
