// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID       int32       `json:"id"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
	Isdelete interface{} `json:"isdelete"`
}
