// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	DeleteAdminLoginById(ctx context.Context, adminID int32) error
	GetAdminById(ctx context.Context, adminID int32) (Admin, error)
}

var _ Querier = (*Queries)(nil)
