package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/pkg/errors"
	echoSwagger "github.com/swaggo/echo-swagger"
	db "github.com/tetrex/golang-project-template/db/sqlc"
	_ "github.com/tetrex/golang-project-template/docs" // docs is generated by Swag CLI
	"github.com/tetrex/golang-project-template/utils/config"
	"github.com/tetrex/golang-project-template/utils/logger"
)

// @title			server api
// @version			1.0
// @description		This is a backend api server
// @contact.name	github.com/tetrex
// @license.name	MIT License
//
// @host			localhost:8000
// @basePath		/
func main() {
	l := logger.New(true)

	// load config
	config, err := config.LoadConfig()
	if err != nil {
		l.Fatal().Err(errors.Errorf("cannot load config "))
		l.Fatal().Err(err)
	}

	// pg connection
	db_config, err := pgxpool.ParseConfig(config.PgConnStr)
	if err != nil {
		l.Fatal().Err(errors.Errorf("cannot connect to to db"))
	}

	db_config.MaxConns = 20                     // Maximum number of connections in the pool
	db_config.MaxConnLifetime = 5 * time.Minute // Maximum lifetime of a connection
	db_config.MaxConnIdleTime = 2 * time.Minute // Maximum time a connection can remain idle

	// ------------
	db_pool, err := pgxpool.NewWithConfig(context.Background(), db_config)
	if err != nil {
		l.Fatal().Err(errors.Errorf("cannot connect to db db_pool"))
	}
	defer db_pool.Close()
	queries := db.New(db_pool)

	s, err := NewServer(ServerParams{
		Config:  config,
		Logger:  l,
		Queries: queries,
	})
	if err != nil {
		l.Fatal().Err(errors.Errorf("cannot create new server"))
	}

	router := s.GetRouter()
	services := s.GetServices()

	router.GET("/", services.Health.HealthCheck)

	router.GET("docs/*", echoSwagger.WrapHandler)

	l.Info().Msgf("docs v1 at :: http://localhost:%d/docs/index.html \n", 8000)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	// some specific tasks
	switch config.AppEnv {
	case "stage":
	case "prod":
		go func() {
			// ---
			server_crt := "/ssl_cert/combined.crt"
			server_key := "/ssl_cert/star_lykstage_com.key"

			l.Log().Msgf("Starting server :: %d", 443)
			if err := router.StartTLS(
				fmt.Sprintf(":%d", 443), server_crt, server_key); err != nil && err != http.ErrServerClosed {
				l.Fatal().Err(err)
				l.Fatal().Err(errors.Errorf("Server startup failed"))
			}
		}()
	case "local":
	default:
		go func() {
			// ---
			l.Log().Msgf("Starting server :: %d", 80)
			if err := router.Start(
				fmt.Sprintf(":%d", 80)); err != nil && err != http.ErrServerClosed {
				l.Fatal().Err(errors.Errorf("Server startup failed"))
			}
		}()
	}

	<-ctx.Done()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := router.Shutdown(ctx); err != nil {
		l.Fatal().Err(err)
		l.Fatal().Err(errors.Errorf("shutting down server gracefully .."))
	}
}
